services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=ng_cash_database
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/app:ro
    environment:
      - NODE_ENV=docker
